root = "."
tmp_dir = "/tmp"
[build]
  args_bin = []
  pre_cmd = []
  cmd = "CGO_ENABLED=0 go build ${GO_BUILD_FLAGS} -ldflags=\"${GO_LD_FLAGS}\" -o ./bin/memory-service ."
  post_cmd = []
  full_bin = "TERM=dumb dlv --continue --listen=:2345 --api-version=2 --only-same-user=false --headless --accept-multiclient exec -- ./bin/memory-service serve"
  # full_bin = "./bin/memory-service serve"
  bin = "TERM=dumb ./bin/memory-service"
  delay = 1000
  exclude_dir = []
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  include_dir = ["internal"]
  include_ext = ["go", "sql"]
  include_file = ["main.go", "go.mod", "go.sum"]
  kill_delay = "0s"
  log = "./build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = false
