apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: memory-service

configMapGenerator:
  - name: memory-service-config
    literals:
      - MEMORY_SERVICE_DB_KIND=postgres
      - MEMORY_SERVICE_CACHE_KIND=none
      - MEMORY_SERVICE_VECTOR_KIND=none
      - MEMORY_SERVICE_ATTACHMENTS_KIND=db
      - MEMORY_SERVICE_MANAGEMENT_PORT=8085

secretGenerator:
  - name: memory-service-secret
    literals: []
