apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: memory-service

configMapGenerator:
  - name: memory-service-config
    literals:
      - MEMORY_SERVICE_DATASTORE_TYPE=postgres
      - MEMORY_SERVICE_CACHE_TYPE=none
      - MEMORY_SERVICE_VECTOR_STORE_TYPE=none
      - MEMORY_SERVICE_ATTACHMENTS_STORE=db

secretGenerator:
  - name: memory-service-secret
    literals: []
