apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Demo: PostgreSQL + Infinispan + pgvector + Keycloak + Monitoring + Chat App
namespace: memory-service

resources:
  - ../postgresql-infinispan

components:
  - ../../components/demo/chat
