apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: chat-quarkus
  namespace: memory-service
spec:
  parentRefs:
    - name: memory-service-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: chat-quarkus
          port: 8080
