apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: memory-service-config
    behavior: merge
    literals:
      - MEMORY_SERVICE_DATASTORE_TYPE=postgres
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/memory_service
      - MEMORY_SERVICE_DATASTORE_MIGRATE_AT_START=true

secretGenerator:
  - name: postgresql-secret
    literals:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memory_service
  - name: memory-service-secret
    behavior: merge
    literals:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
