apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
  namespace: memory-service
spec:
  parentRefs:
    - name: memory-service-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /realms/
      backendRefs:
        - name: keycloak
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /admin/
      backendRefs:
        - name: keycloak
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /resources/
      backendRefs:
        - name: keycloak
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /js/
      backendRefs:
        - name: keycloak
          port: 8080
