kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 10080
        hostPort: 80
        protocol: TCP
      - containerPort: 10443
        hostPort: 443
        protocol: TCP
