apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../overlays/postgresql-infinispan

components:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: memory-service-config
    patch: |
      - op: add
        path: /data/MEMORY_SERVICE_EMBEDDING_TYPE
        value: openai
